[package]
name = "librocksdb-sys"
version = "0.17.2+8.10.2"
edition = "2018"
rust-version = "1.85"
authors = ["Karl Hobley <karlhobley10@gmail.com>", "Arkadiy Paronyan <arkadiy@ethcore.io>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
description = "Native bindings to librocksdb"
readme = "README.md"
repository = "https://github.com/rust-rocksdb/rust-rocksdb"
keywords = [ "bindings", "ffi", "rocksdb" ]
categories = [ "api-bindings", "database", "external-ffi-bindings" ]
links = "rocksdb"

[features]
default = [ "jemalloc" ]
jemalloc = ["tikv-jemalloc-sys"]
# deprecated: linking is always dynamic now
static = []
# deprecated: no longer relevant
mt_static = []
# deprecated: io-uring is baked into librocksdb.so
io-uring = []
rtti = []

[dependencies]
libc = "0.2"
tikv-jemalloc-sys = { version = "0.5", features = ["unprefixed_malloc_on_supported_platforms"], optional = true }

[dev-dependencies]
uuid = { version = "1.0", features = ["v4"] }

[build-dependencies]
bindgen = { version = "0.69", default-features = false, features = ["runtime"] }
num_cpus = "1.0"