name: ToplingDB CI

on: [ push, pull_request ]
env:
  RUST_VERSION: 1.85

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  doc-check:
    name: Rustdoc-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rust-docs
      - name: Run cargo rustdoc
        run: cargo rustdoc -- -D warnings

  audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: actions-rust-lang/audit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y
          libcurl4-openssl-dev
          liburing-dev
          libaio-dev
          pkg-config
          zlib1g-dev
          libbz2-dev
          liblz4-dev
          libsnappy-dev
          libzstd-dev
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests (default features)
        run: cargo test --workspace
      - name: Run tests (multi-threaded-cf)
        run: cargo test --workspace --features multi-threaded-cf
      - name: Run tests (all features)
        run: cargo test --workspace --all-features
